# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sihao Chen
author: Sihao Chen
author_link: https://www.seas.upenn.edu/~sihaoc/
author_position: Research Assistant
email: sihaoc [at] seas [dot] upenn [dot] edu
description: > # this means to ignore newlines until "baseurl:"
  Sihao Chen - Research Assistant at University of Pennsylvania
baseurl: "/~sihaoc/" # the subpath of your site, e.g. /blog
url: "https://www.seas.upenn.edu/" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
#permalink: pretty

# Pagination
paginate: 5
paginate_path: "_posts/page:num/"

# Sass
sass:
    style: :compressed
